# -*- coding: utf-8 -*-
"""Avaliação da solução.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# -*- coding: utf-8 -*-
"""Aprendizado Supervisionado vs Não Supervisionado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# Aprendizado Supervisionado vs Não Supervisionado

# Aprendizado Supervisionado
# No aprendizado supervisionado, fornecemos ao algoritmo exemplos com respostas corretas (rótulos).
# O modelo aprende a associar entradas às saídas e tenta prever a saída correta para novos dados.

# Exemplos:
# - Prever se um e-mail é spam ou não spam (classificação)
# - Estimar o valor de um imóvel (regressão)

# Chave: existe uma coluna de “gabarito” que queremos prever.

# ------------------------------------------------------------

# Aprendizado Não Supervisionado
# Aqui o modelo recebe apenas os dados de entrada, sem rótulos.
# O objetivo é descobrir padrões escondidos, como agrupar elementos semelhantes.

# Exemplos:
# - Separar clientes em grupos de comportamento semelhante
# - Detectar tópicos comuns em textos sem saber o tema de cada um

# Chave: não há respostas certas, só padrões nos dados.

# ------------------------------------------------------------

# Exercício: Classifique os problemas abaixo como Supervisionado ou Não Supervisionado

respostas = {
    "Prever se uma pessoa vai cancelar sua assinatura": "Aprendizado Supervisionado",  # Temos rótulos: cancelou ou não cancelou
    "Agrupar músicas por estilo com base em frequência sonora": "Aprendizado Não Supervisionado",  # Sem rótulos, buscamos padrões sonoros
    "Prever a nota média que um filme vai receber": "Aprendizado Supervisionado",  # Usamos notas anteriores como rótulo
    "Agrupar pacientes por padrões em exames de sangue": "Aprendizado Não Supervisionado",  # Descobrimos grupos sem rótulos
    "Identificar se uma imagem mostra um gato ou cachorro": "Aprendizado Supervisionado"  # Imagens rotuladas como gato ou cachorro
}

# Exibir todas as respostas
for problema, tipo in respostas.items():
    print(f"{problema}: {tipo}")