# -*- coding: utf-8 -*-
"""Avaliação da solução.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# 1) Importa bibliotecas necessárias
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# 2) Cria um conjunto de dados fictício com 9 cidadãos
dados = pd.DataFrame({
    'idade': [25, 38, 28, 44, 18, 34, 29, 45, 31],
    'educacao': ['Bachelors', 'HS-grad', 'HS-grad', 'Masters', 'HS-grad', 'Some-college', 'Bachelors', 'Doctorate', 'HS-grad'],
    'horas_por_semana': [40, 50, 40, 60, 20, 45, 40, 55, 35],
    'renda': ['<=50K', '<=50K', '<=50K', '<=50K', '<=50K', '>50K', '<=50K', '<=50K', '>50K']
})

# 3) Codifica a variável categórica 'educacao'
le = LabelEncoder()
dados['educacao'] = le.fit_transform(dados['educacao'])

# 4) Separa os dados em variáveis independentes (X) e alvo (y)
X = dados[['idade', 'educacao', 'horas_por_semana']]
y = dados['renda'].apply(lambda x: 0 if x == '<=50K' else 1)

# 5) Divide em treino e teste (40% para teste, sem erro!)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# 6) Cria e treina o modelo de árvore de decisão
modelo = DecisionTreeClassifier()
modelo.fit(X_train, y_train)

# 7) Faz previsões com os dados de teste
y_pred = modelo.predict(X_test)

# 8) Exibe as previsões para os cidadãos do conjunto de teste
print("Previsões de renda para cidadãos americanos:\n")
for i in range(len(y_pred)):
    prediction = "<=50K" if y_pred[i] == 0 else ">=50K"
    print(f"Cidadão {i+1}: {prediction}")
    print("---")