# -*- coding: utf-8 -*-
"""Importâncias das features do modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# Análise de Importância das Características no Modelo Random Forest

# ------------------------------------------------------------
# Obtendo as importâncias das features do modelo treinado
# Cada valor representa o quanto uma feature contribui para as decisões do modelo
feature_importances = best_rf.feature_importances_

# ------------------------------------------------------------
# Recuperando os nomes das features
# No caso do dataset de vinhos, os nomes estão disponíveis em 'data.feature_names'
feature_names = data.feature_names

# ------------------------------------------------------------
# Criando uma lista de tuplas (nome_da_feature, importância)
# Ordenamos da mais importante para a menos importante
features_sorted = sorted(
    zip(feature_names, feature_importances),
    key=lambda x: x[1],
    reverse=True
)

# ------------------------------------------------------------
# 📈 Imprimindo as features ordenadas por importância
print("Importância das características no modelo otimizado (da mais importante para a menos importante):")
for feature, importance in features_sorted:
    print(f"{feature}: {importance:.5f}")