# -*- coding: utf-8 -*-
"""Métricas de Avaliação do Modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# Avaliação Final com o Melhor Modelo Otimizado

# ------------------------------------------------------------
# Recuperando o melhor modelo encontrado pelo Grid Search
# O método 'best_estimator_' retorna o modelo com a melhor combinação de hiperparâmetros
best_rf = grid_search.best_estimator_

# ------------------------------------------------------------
# Fazendo previsões com o modelo otimizado no conjunto de teste
y_test_pred = best_rf.predict(X_test)

# ------------------------------------------------------------
# Calculando o F1-score no conjunto de teste
# Usamos a média macro para considerar todas as classes igualmente
test_f1 = f1_score(y_test, y_test_pred, average='macro')
print(f"F1-score no teste (macro): {test_f1:.4f}")

# ------------------------------------------------------------
# 📋 Exibindo o relatório de classificação completo
# Mostra precisão, recall e F1-score por classe
print("\nRelatório de classificação do melhor modelo:")
print(classification_report(y_test, y_test_pred, target_names=data.target_names))