# -*- coding: utf-8 -*-
"""Número Ideal de Clusters com o Método do Cotovelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# Encontrando o Número Ideal de Clusters com o Método do Cotovelo

# ------------------------------------------------------------
# Objetivo:
# Utilizar o K-Means com diferentes valores de K (número de clusters)
# e calcular o WCSS (Within-Cluster Sum of Squares) para cada um.
# O ponto onde o WCSS deixa de cair significativamente é chamado de "cotovelo".

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Calculando o WCSS para K variando de 1 a 10
wcss = []
for k in range(1, 11):
    kmeans = KMeans(
        n_clusters=k,
        init='k-means++',       # Inicialização inteligente dos centroides
        n_init=10,              # Número de inicializações diferentes
        max_iter=300,           # Número máximo de iterações
        random_state=0          # Reprodutibilidade
    )
    kmeans.fit(X)              # X deve conter os dados que você quer agrupar
    wcss.append(kmeans.inertia_)  # inertia_ = WCSS

# ------------------------------------------------------------
# 2. Plotando o gráfico do Método do Cotovelo
plt.figure(figsize=(8, 5))
plt.plot(range(1, 11), wcss, marker='o', color='blue')
plt.title('Método do Cotovelo (Elbow Method)')
plt.xlabel('Número de Clusters')
plt.ylabel('WCSS (inertia)')
plt.grid(True)

# ------------------------------------------------------------
# 3. Destacando o ponto de cotovelo (exemplo: K=4)
# Você pode ajustar esse valor com base na curva observada
cotovelo_k = 4
plt.plot(cotovelo_k, wcss[cotovelo_k - 1], 'ro')  # ponto de cotovelo
plt.annotate(
    f'Cotovelo (K ideal = {cotovelo_k})',
    xy=(cotovelo_k, wcss[cotovelo_k - 1]),
    xytext=(cotovelo_k + 1, wcss[cotovelo_k - 1] + 500),
    arrowprops=dict(facecolor='black', shrink=0.05)
)

plt.show()