# -*- coding: utf-8 -*-
"""Treinamento do K-Means com K=4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16egLGyFK68yCO7gp8gnXaAh1XMFFd6xI
"""

# Treinamento do K-Means com K=4

# ------------------------------------------------------------
# Inicializando e treinando o modelo K-Means
# Usamos o valor de K ideal encontrado pelo método do cotovelo (ex: K=4)
from sklearn.cluster import KMeans

kmeans_final = KMeans(
    n_clusters=4,       # Número de clusters
    init='k-means++',   # Inicialização inteligente dos centroides
    n_init=10,          # Número de inicializações diferentes
    max_iter=300,       # Número máximo de iterações
    random_state=42     # Reprodutibilidade
)

# Aplicando o modelo aos dados
# 'fit_predict' treina o modelo e retorna os rótulos de cluster para cada ponto
y_kmeans_final = kmeans_final.fit_predict(X)

# ------------------------------------------------------------
# Visualização dos Clusters Resultantes

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))

# Cluster 1
plt.scatter(X[y_kmeans_final == 0, 0], X[y_kmeans_final == 0, 1],
            s=100, c='red', label='Cluster 1')

# Cluster 2
plt.scatter(X[y_kmeans_final == 1, 0], X[y_kmeans_final == 1, 1],
            s=100, c='blue', label='Cluster 2')

# Cluster 3
plt.scatter(X[y_kmeans_final == 2, 0], X[y_kmeans_final == 2, 1],
            s=100, c='green', label='Cluster 3')

# Cluster 4
plt.scatter(X[y_kmeans_final == 3, 0], X[y_kmeans_final == 3, 1],
            s=100, c='orange', label='Cluster 4')

# Centróides dos clusters
plt.scatter(kmeans_final.cluster_centers_[:, 0], kmeans_final.cluster_centers_[:, 1],
            s=300, c='magenta', label='Centróides')

# Configurações do gráfico
plt.title('📌 Clusters de Dados Encontrados pelo K-Means')
plt.xlabel('Atributo 1')
plt.ylabel('Atributo 2')
plt.legend()
plt.grid(True)
plt.show()